-define(tz_index,
    #{"ADT" =>
          ["America/Moncton","America/Glace_Bay","America/Goose_Bay","Canada/Atlantic",
           "America/Thule","America/Halifax","Atlantic/Bermuda"],
      "+12" =>
          ["Asia/Anadyr","Pacific/Wake","Pacific/Tarawa","Pacific/Funafuti","Etc/GMT-12",
           "Kwajalein","Pacific/Majuro","Pacific/Wallis","Asia/Kamchatka","Pacific/Kwajalein",
           "Pacific/Fiji","Pacific/Nauru"],
      "SAST" => ["Africa/Maseru","Africa/Mbabane","Africa/Johannesburg"],
      "CEST" =>
          ["Europe/Gibraltar","Atlantic/Jan_Mayen","Europe/Amsterdam","Europe/Ljubljana",
           "Europe/Podgorica","Europe/Stockholm","CET","Europe/Berlin","Europe/Budapest",
           "Europe/Zagreb","Europe/Oslo","Europe/Zurich","Africa/Ceuta","Europe/Bratislava",
           "Europe/Busingen","Europe/Vaduz","Europe/Madrid","Europe/San_Marino",
           "Europe/Luxembourg","Poland","Europe/Andorra","Europe/Skopje","Europe/Warsaw",
           "Europe/Paris","Arctic/Longyearbyen","Europe/Vienna","Europe/Tirane","Europe/Sarajevo",
           "Europe/Brussels","Europe/Rome","Europe/Copenhagen","Europe/Monaco","Europe/Belgrade",
           "Europe/Vatican","Europe/Malta","Europe/Prague"],
      "MST" =>
          ["MST","America/Phoenix","America/Cambridge_Bay","America/Inuvik","America/Boise",
           "America/Edmonton","America/Denver","US/Arizona","America/Fort_Nelson",
           "America/Chihuahua","America/Creston","Navajo","America/Shiprock","America/Mazatlan",
           "Canada/Mountain","US/Mountain","America/Dawson_Creek","Mexico/BajaSur",
           "America/Hermosillo","MST7MDT","America/Ojinaga","America/Yellowknife"],
      "IST" =>
          ["Asia/Jerusalem","Asia/Tel_Aviv","Eire","Europe/Dublin","Asia/Kolkata","Israel",
           "Asia/Calcutta"],
      "GMT" =>
          ["Etc/GMT0","Europe/Guernsey","Africa/Bamako","GMT","Greenwich","Etc/GMT+0","GB",
           "Africa/Nouakchott","GMT0","GMT-0","Africa/Bissau","Europe/London","Africa/Conakry",
           "GMT+0","Etc/GMT","Africa/Dakar","Africa/Abidjan","Eire","Europe/Dublin",
           "Africa/Ouagadougou","Africa/Lome","Europe/Jersey","Atlantic/Reykjavik",
           "Africa/Monrovia","Iceland","Europe/Belfast","Africa/Freetown","America/Danmarkshavn",
           "Etc/GMT-0","GB-Eire","Africa/Timbuktu","Europe/Isle_of_Man","Etc/Greenwich",
           "Africa/Banjul","Atlantic/St_Helena"],
      "JST" => ["Japan","Asia/Tokyo"],
      "AEST" =>
          ["Australia/Hobart","Australia/Melbourne","Australia/Tasmania","Australia/Lindeman",
           "Australia/Queensland","Australia/Victoria","Australia/Brisbane","Australia/ACT",
           "Australia/Canberra","Australia/Currie","Australia/Sydney","Australia/NSW"],
      "-10/-0930" => ["Pacific/Rarotonga"],
      "CAT" =>
          ["Africa/Harare","Africa/Gaborone","Africa/Windhoek","Africa/Bujumbura","Africa/Lusaka",
           "Africa/Khartoum","Africa/Blantyre","Africa/Kigali","Africa/Maputo",
           "Africa/Lubumbashi"],
      "-10" => ["Etc/GMT+10","Pacific/Tahiti"],
      "NZST" => ["Antarctica/McMurdo","Pacific/Auckland","NZ","Antarctica/South_Pole"],
      "AEDT" =>
          ["Australia/Hobart","Australia/Melbourne","Australia/Tasmania","Australia/Victoria",
           "Australia/ACT","Australia/Canberra","Australia/Currie","Australia/Sydney",
           "Australia/NSW"],
      "CST" =>
          ["America/Bahia_Banderas","America/Merida","America/Rainy_River","US/Central",
           "America/Tegucigalpa","America/Managua","America/Guatemala","America/Monterrey",
           "Asia/Harbin","America/Rankin_Inlet","Mexico/General","Asia/Taipei",
           "America/Matamoros","America/Regina","America/Indiana/Tell_City","PRC",
           "US/Indiana-Starke","America/Indiana/Knox","America/North_Dakota/Center",
           "America/Knox_IN","America/Costa_Rica","America/Belize","America/Menominee",
           "Canada/Central","Asia/Macao","America/Mexico_City","Asia/Chongqing",
           "America/North_Dakota/New_Salem","America/Havana","Asia/Macau","Cuba","Asia/Chungking",
           "Canada/Saskatchewan","America/North_Dakota/Beulah","America/El_Salvador","ROC",
           "Asia/Shanghai","America/Resolute","CST6CDT","America/Swift_Current","America/Chicago",
           "America/Winnipeg"],
      "+10" =>
          ["Antarctica/DumontDUrville","Pacific/Chuuk","Etc/GMT-10","Pacific/Port_Moresby",
           "Pacific/Yap","Asia/Ust-Nera","Pacific/Truk","Asia/Vladivostok"],
      "AWST" => ["Australia/West","Australia/Perth"],
      "CDT" =>
          ["America/Bahia_Banderas","America/Merida","America/Rainy_River","US/Central",
           "America/Monterrey","America/Rankin_Inlet","Mexico/General","America/Matamoros",
           "America/Indiana/Tell_City","US/Indiana-Starke","America/Indiana/Knox",
           "America/North_Dakota/Center","America/Knox_IN","America/Menominee","Canada/Central",
           "America/Mexico_City","America/North_Dakota/New_Salem","America/Havana","Cuba",
           "America/North_Dakota/Beulah","America/Resolute","CST6CDT","America/Chicago",
           "America/Winnipeg"],
      "+06" =>
          ["Asia/Urumqi","Asia/Omsk","Asia/Kashgar","Asia/Almaty","Asia/Bishkek","Etc/GMT-6",
           "Asia/Thimphu","Indian/Chagos","Asia/Qyzylorda","Antarctica/Vostok","Asia/Thimbu"],
      "WITA" => ["Asia/Makassar","Asia/Ujung_Pandang"],
      "+0630" => ["Asia/Rangoon","Indian/Cocos","Asia/Yangon"],
      "+1345" => ["Pacific/Chatham","NZ-CHAT"],
      "CET" =>
          ["Europe/Gibraltar","Atlantic/Jan_Mayen","Europe/Amsterdam","Europe/Ljubljana",
           "Europe/Podgorica","Europe/Stockholm","CET","Europe/Berlin","Europe/Budapest",
           "Europe/Zagreb","Africa/Tunis","Europe/Oslo","Europe/Zurich","Africa/Ceuta",
           "Europe/Bratislava","Europe/Busingen","Europe/Vaduz","Europe/Madrid",
           "Europe/San_Marino","Europe/Luxembourg","Poland","Europe/Andorra","Europe/Skopje",
           "Europe/Warsaw","Europe/Paris","Arctic/Longyearbyen","Europe/Vienna","Europe/Tirane",
           "Europe/Sarajevo","Africa/Algiers","Europe/Brussels","Europe/Rome","Europe/Copenhagen",
           "Europe/Monaco","Europe/Belgrade","Europe/Vatican","Europe/Malta","Europe/Prague"],
      "-04" =>
          ["America/Boa_Vista","America/Guyana","Chile/Continental","America/Campo_Grande",
           "America/Manaus","America/Asuncion","Etc/GMT+4","America/Cuiaba","America/La_Paz",
           "America/Porto_Velho","Brazil/West","America/Caracas","America/Santiago"],
      "-03/-02" =>
          ["America/Argentina/Cordoba","America/Argentina/Tucuman","America/Montevideo",
           "America/Rosario","America/Cordoba","America/Buenos_Aires",
           "America/Argentina/Buenos_Aires"],
      "-09" => ["Etc/GMT+9","Pacific/Gambier"],
      "AKDT" =>
          ["America/Anchorage","America/Juneau","America/Metlakatla","America/Nome",
           "America/Sitka","US/Alaska","America/Yakutat"],
      "-06/-05" => ["Pacific/Galapagos"],
      "KST" => ["Asia/Seoul","Asia/Pyongyang","ROK"],
      "PKT" => ["Asia/Karachi"],
      "NZDT" => ["Antarctica/McMurdo","Pacific/Auckland","NZ","Antarctica/South_Pole"],
      "EEST" =>
          ["Asia/Beirut","Europe/Sofia","Europe/Mariehamn","Europe/Bucharest","Europe/Helsinki",
           "Europe/Chisinau","Asia/Nicosia","Europe/Uzhgorod","Asia/Gaza","Europe/Tiraspol",
           "Asia/Amman","Europe/Tallinn","Europe/Vilnius","EET","Europe/Kiev","Asia/Hebron",
           "Asia/Damascus","Europe/Nicosia","Asia/Famagusta","Europe/Athens","Europe/Zaporozhye",
           "Europe/Riga"],
      "+0330" => ["Asia/Tehran","Iran"],
      "MET" => ["MET"],
      "+00" => ["Antarctica/Troll","Atlantic/Azores","America/Scoresbysund"],
      "MSK" => ["Europe/Simferopol","W-SU","Europe/Moscow"],
      "ACST" =>
          ["Australia/Adelaide","Australia/North","Australia/South","Australia/Broken_Hill",
           "Australia/Darwin","Australia/Yancowinna"],
      "IDT" => ["Asia/Jerusalem","Asia/Tel_Aviv","Israel"],
      "+06/+07" => ["Asia/Dacca","Asia/Dhaka"],
      "-02" =>
          ["America/Godthab","Brazil/DeNoronha","America/Miquelon","America/Noronha","Etc/GMT+2",
           "America/Sao_Paulo","Atlantic/South_Georgia","Brazil/East"],
      "+01" => ["Etc/GMT-1"],
      "-08" => ["Pacific/Pitcairn","Etc/GMT+8"],
      "EAT" =>
          ["Indian/Mayotte","Africa/Djibouti","Africa/Juba","Africa/Asmara","Indian/Comoro",
           "Africa/Mogadishu","Africa/Dar_es_Salaam","Africa/Kampala","Africa/Asmera",
           "Indian/Antananarivo","Africa/Nairobi","Africa/Addis_Ababa"],
      "AST" =>
          ["America/Moncton","America/Santo_Domingo","America/St_Kitts","America/Glace_Bay",
           "America/St_Barthelemy","America/Goose_Bay","America/Virgin","America/Tortola",
           "America/Guadeloupe","America/Curacao","Canada/Atlantic","America/Thule",
           "America/Grenada","America/Kralendijk","America/Puerto_Rico","America/Barbados",
           "America/Marigot","America/Halifax","Atlantic/Bermuda","America/Montserrat",
           "America/Blanc-Sablon","America/Lower_Princes","America/St_Lucia","America/St_Thomas",
           "America/Dominica","America/Port_of_Spain","America/Martinique","America/St_Vincent",
           "America/Antigua","America/Aruba","America/Anguilla"],
      "-03" =>
          ["America/Argentina/ComodRivadavia","Antarctica/Palmer","America/Santarem",
           "America/Argentina/San_Luis","America/Recife","America/Bahia","America/Godthab",
           "America/Argentina/Mendoza","Chile/Continental","America/Jujuy","Atlantic/Stanley",
           "America/Miquelon","America/Campo_Grande","America/Asuncion","America/Maceio",
           "America/Fortaleza","America/Argentina/Rio_Gallegos","America/Argentina/Ushuaia",
           "America/Cuiaba","America/Belem","America/Mendoza","America/Cayenne",
           "America/Argentina/Salta","Antarctica/Rothera","America/Sao_Paulo","America/Catamarca",
           "America/Argentina/Catamarca","America/Paramaribo","America/Argentina/San_Juan",
           "America/Argentina/Jujuy","Etc/GMT+3","Brazil/East","America/Araguaina",
           "America/Argentina/La_Rioja","America/Santiago","America/Punta_Arenas"],
      "+0530" => ["Asia/Colombo"],
      "SST" => ["US/Samoa","Pacific/Samoa","Pacific/Pago_Pago","Pacific/Midway"],
      "+13/+14" => ["Pacific/Tongatapu"],
      "HDT" => ["America/Atka","US/Aleutian","America/Adak"],
      "+1245" => ["Pacific/Chatham","NZ-CHAT"],
      "HST" =>
          ["Pacific/Honolulu","America/Atka","US/Aleutian","HST","US/Hawaii","America/Adak",
           "Pacific/Johnston"],
      "ACDT" =>
          ["Australia/Adelaide","Australia/South","Australia/Broken_Hill","Australia/Yancowinna"],
      "+14" => ["Pacific/Apia","Etc/GMT-14","Pacific/Kiritimati"],
      "BST" =>
          ["Europe/Guernsey","GB","Europe/London","Europe/Jersey","Europe/Belfast","GB-Eire",
           "Europe/Isle_of_Man"],
      "+0545" => ["Asia/Kathmandu","Asia/Katmandu"],
      "+03" =>
          ["Etc/GMT-3","Asia/Istanbul","Turkey","Asia/Riyadh","Europe/Istanbul",
           "Antarctica/Syowa","Asia/Kuwait","Europe/Kirov","Europe/Minsk","Asia/Aden",
           "Europe/Volgograd","Asia/Bahrain","Asia/Qatar"],
      "+02" => ["Antarctica/Troll","Etc/GMT-2"],
      "-06" => ["Chile/EasterIsland","Etc/GMT+6","Pacific/Easter"],
      "EET" =>
          ["Libya","Asia/Beirut","Europe/Sofia","Europe/Mariehamn","Europe/Bucharest",
           "Europe/Helsinki","Europe/Chisinau","Asia/Nicosia","Europe/Uzhgorod","Asia/Gaza",
           "Europe/Tiraspol","Asia/Amman","Europe/Tallinn","Europe/Vilnius","Egypt",
           "Europe/Kaliningrad","EET","Africa/Tripoli","Africa/Cairo","Europe/Kiev","Asia/Hebron",
           "Asia/Damascus","Europe/Nicosia","Asia/Famagusta","Europe/Athens","Europe/Zaporozhye",
           "Europe/Riga"],
      "UTC" => ["Etc/Universal","Zulu","UTC","Universal","Etc/UTC","Etc/Zulu"],
      "WIT" => ["Asia/Jayapura"],
      "-11" => ["Etc/GMT+11","Pacific/Niue"],
      "+04" =>
          ["Asia/Tbilisi","Etc/GMT-4","Indian/Reunion","Europe/Saratov","Indian/Mahe",
           "Asia/Muscat","Europe/Samara","Europe/Ulyanovsk","Asia/Dubai","Europe/Astrakhan"],
      "AKST" =>
          ["America/Anchorage","America/Juneau","America/Metlakatla","America/Nome",
           "America/Sitka","US/Alaska","America/Yakutat"],
      "+1030" => ["Australia/LHI","Australia/Lord_Howe"],
      "-12" => ["Etc/GMT+12"],
      "+07/+08" => ["Asia/Hovd"],
      "+11/+12" => ["Pacific/Efate","Pacific/Noumea"],
      "WIB" => ["Asia/Pontianak","Asia/Jakarta"],
      "HKT" => ["Hongkong","Asia/Hong_Kong"],
      "PST" =>
          ["America/Dawson","Mexico/BajaNorte","America/Los_Angeles","America/Santa_Isabel",
           "America/Tijuana","Canada/Pacific","US/Pacific","America/Ensenada",
           "America/Whitehorse","America/Vancouver","PST8PDT","Canada/Yukon"],
      "EST" =>
          ["America/Panama","America/Fort_Wayne","America/Coral_Harbour",
           "America/Kentucky/Louisville","America/Indiana/Vincennes","US/East-Indiana",
           "America/Grand_Turk","America/Cayman","America/Indiana/Vevay","Jamaica",
           "America/Kentucky/Monticello","America/Nipigon","America/Jamaica",
           "America/Indiana/Petersburg","America/Atikokan","America/Indiana/Winamac",
           "America/Montreal","America/Louisville","America/New_York","America/Thunder_Bay","EST",
           "US/Eastern","America/Indiana/Indianapolis","America/Iqaluit","America/Port-au-Prince",
           "America/Cancun","Canada/Eastern","America/Pangnirtung","US/Michigan",
           "America/Indiana/Marengo","EST5EDT","America/Toronto","America/Detroit",
           "America/Nassau","America/Indianapolis"],
      "+08" =>
          ["Singapore","Asia/Brunei","Antarctica/Casey","Asia/Kuching","Asia/Irkutsk","Etc/GMT-8",
           "Asia/Kuala_Lumpur","Asia/Singapore"],
      "+08/+09" => ["Asia/Ulaanbaatar","Asia/Ulan_Bator","Asia/Manila","Asia/Choibalsan"],
      "-01" => ["Atlantic/Cape_Verde","Etc/GMT+1","Atlantic/Azores","America/Scoresbysund"],
      "PDT" =>
          ["America/Dawson","Mexico/BajaNorte","America/Los_Angeles","America/Santa_Isabel",
           "America/Tijuana","Canada/Pacific","US/Pacific","America/Ensenada",
           "America/Whitehorse","America/Vancouver","PST8PDT","Canada/Yukon"],
      "UCT" => ["UCT","Etc/UCT"],
      "MEST" => ["MET"],
      "WAT" =>
          ["Africa/Libreville","Africa/Kinshasa","Africa/Brazzaville","Africa/Porto-Novo",
           "Africa/Ndjamena","Africa/Bangui","Africa/Douala","Africa/Niamey","Africa/Sao_Tome",
           "Africa/Malabo","Africa/Luanda","Africa/Lagos"],
      "+0845/+0945" => ["Australia/Eucla"],
      "+13" => ["Etc/GMT-13","Pacific/Fakaofo","Pacific/Apia","Pacific/Enderbury","Pacific/Fiji"],
      "+04/+05" => ["Asia/Baku","Asia/Yerevan","Indian/Mauritius"],
      "EDT" =>
          ["America/Fort_Wayne","America/Kentucky/Louisville","America/Indiana/Vincennes",
           "US/East-Indiana","America/Grand_Turk","America/Indiana/Vevay",
           "America/Kentucky/Monticello","America/Nipigon","America/Indiana/Petersburg",
           "America/Indiana/Winamac","America/Montreal","America/Louisville","America/New_York",
           "America/Thunder_Bay","US/Eastern","America/Indiana/Indianapolis","America/Iqaluit",
           "America/Port-au-Prince","Canada/Eastern","America/Pangnirtung","US/Michigan",
           "America/Indiana/Marengo","EST5EDT","America/Toronto","America/Detroit",
           "America/Nassau","America/Indianapolis"],
      "-07" => ["Etc/GMT+7"],
      "GMT/+0020" => ["Africa/Accra"],
      "ChST" => ["Pacific/Guam","Pacific/Saipan"],
      "-05" =>
          ["Etc/GMT+5","Chile/EasterIsland","America/Rio_Branco","America/Porto_Acre",
           "Brazil/Acre","Pacific/Easter","America/Eirunepe"],
      "+0430" => ["Asia/Tehran","Iran","Asia/Kabul"],
      "WET" =>
          ["Atlantic/Canary","Portugal","Atlantic/Faeroe","Africa/El_Aaiun","Atlantic/Faroe",
           "Atlantic/Madeira","Europe/Lisbon","WET","Africa/Casablanca"],
      "MDT" =>
          ["America/Cambridge_Bay","America/Inuvik","America/Boise","America/Edmonton",
           "America/Denver","America/Chihuahua","Navajo","America/Shiprock","America/Mazatlan",
           "Canada/Mountain","US/Mountain","Mexico/BajaSur","MST7MDT","America/Ojinaga",
           "America/Yellowknife"],
      "+07" =>
          ["Asia/Barnaul","Indian/Christmas","Asia/Novokuznetsk","Etc/GMT-7","Asia/Krasnoyarsk",
           "Asia/Bangkok","Asia/Saigon","Antarctica/Davis","Asia/Novosibirsk","Asia/Ho_Chi_Minh",
           "Asia/Tomsk","Asia/Phnom_Penh","Asia/Vientiane"],
      "+09" =>
          ["Asia/Yakutsk","Pacific/Palau","Asia/Dili","Asia/Khandyga","Asia/Chita","Etc/GMT-9"],
      "NST" => ["Canada/Newfoundland","America/St_Johns"],
      "-0930" => ["Pacific/Marquesas"],
      "+11" =>
          ["Australia/LHI","Pacific/Pohnpei","Asia/Sakhalin","Pacific/Ponape",
           "Australia/Lord_Howe","Asia/Srednekolymsk","Etc/GMT-11","Pacific/Norfolk",
           "Antarctica/Macquarie","Asia/Magadan","Pacific/Kosrae","Pacific/Guadalcanal",
           "Pacific/Bougainville"],
      "+05" =>
          ["Asia/Aqtau","Antarctica/Mawson","Asia/Samarkand","Asia/Yekaterinburg","Etc/GMT-5",
           "Asia/Ashgabat","Asia/Oral","Asia/Dushanbe","Indian/Kerguelen","Indian/Maldives",
           "Asia/Atyrau","Asia/Ashkhabad","Asia/Tashkent","Asia/Aqtobe"],
      "WEST" =>
          ["Atlantic/Canary","Portugal","Atlantic/Faeroe","Africa/El_Aaiun","Atlantic/Faroe",
           "Atlantic/Madeira","Europe/Lisbon","WET","Africa/Casablanca"],
      "+03/+04" => ["Asia/Baghdad"],
      "-05/-04" => ["America/Bogota","America/Lima","America/Guayaquil"],
      "NDT" => ["Canada/Newfoundland","America/St_Johns"]}).
