-define(tz_index,
  #{"NDT" => ["America/St_Johns","Canada/Newfoundland"],
    "-05/-04" => ["America/Guayaquil","America/Lima","America/Bogota"],
    "+03/+04" => ["Asia/Baghdad"],
    "WEST" =>
    ["WET","Europe/Lisbon","Atlantic/Madeira","Atlantic/Faroe","Atlantic/Faeroe","Portugal",
      "Atlantic/Canary"],
    "+05" =>
    ["Asia/Aqtobe","Asia/Qyzylorda","Asia/Tashkent","Asia/Ashkhabad","Asia/Atyrau",
      "Indian/Maldives","Indian/Kerguelen","Asia/Dushanbe","Asia/Oral","Asia/Ashgabat",
      "Etc/GMT-5","Asia/Yekaterinburg","Asia/Samarkand","Antarctica/Mawson","Asia/Aqtau"],
    "+11" =>
    ["Pacific/Bougainville","Pacific/Guadalcanal","Pacific/Kosrae","Asia/Magadan",
      "Pacific/Norfolk","Etc/GMT-11","Asia/Srednekolymsk","Australia/Lord_Howe",
      "Pacific/Ponape","Antarctica/Casey","Asia/Sakhalin","Pacific/Pohnpei","Australia/LHI"],
    "-0930" => ["Pacific/Marquesas"],
    "NST" => ["America/St_Johns","Canada/Newfoundland"],
    "+09" =>
    ["Etc/GMT-9","Asia/Chita","Asia/Khandyga","Asia/Dili","Pacific/Palau","Asia/Yakutsk"],
    "+07" =>
    ["Asia/Vientiane","Asia/Phnom_Penh","Asia/Tomsk","Asia/Ho_Chi_Minh","Asia/Novosibirsk",
      "Antarctica/Davis","Asia/Saigon","Asia/Bangkok","Asia/Krasnoyarsk","Etc/GMT-7",
      "Asia/Novokuznetsk","Indian/Christmas","Asia/Barnaul"],
    "MDT" =>
    ["America/Yellowknife","America/Ojinaga","MST7MDT","Mexico/BajaSur","US/Mountain",
      "Canada/Mountain","America/Mazatlan","America/Shiprock","Navajo","America/Chihuahua",
      "America/Denver","America/Edmonton","America/Boise","America/Inuvik",
      "America/Cambridge_Bay"],
    "WET" =>
    ["WET","Europe/Lisbon","Atlantic/Madeira","Atlantic/Faroe","Atlantic/Faeroe","Portugal",
      "Atlantic/Canary"],
    "+0430" => ["Asia/Kabul","Iran","Asia/Tehran"],
    "-05" =>
    ["America/Eirunepe","Pacific/Easter","Brazil/Acre","America/Porto_Acre",
      "America/Rio_Branco","Chile/EasterIsland","Etc/GMT+5"],
    "ChST" => ["Pacific/Saipan","Pacific/Guam"],
    "-07" => ["Etc/GMT+7"],
    "EDT" =>
    ["America/Indianapolis","America/Nassau","America/Detroit","America/Toronto","EST5EDT",
      "America/Indiana/Marengo","US/Michigan","America/Pangnirtung","Canada/Eastern",
      "America/Port-au-Prince","America/Iqaluit","America/Indiana/Indianapolis","US/Eastern",
      "America/Thunder_Bay","America/New_York","America/Louisville","America/Montreal",
      "America/Indiana/Winamac","America/Indiana/Petersburg","America/Nipigon",
      "America/Kentucky/Monticello","America/Indiana/Vevay","America/Grand_Turk",
      "US/East-Indiana","America/Indiana/Vincennes","America/Kentucky/Louisville",
      "America/Fort_Wayne"],
    "+04/+05" => ["Indian/Mauritius","Asia/Yerevan","Asia/Baku"],
    "+13" => ["Pacific/Fiji","Pacific/Enderbury","Pacific/Apia","Pacific/Fakaofo","Etc/GMT-13"],
    "+0845/+0945" => ["Australia/Eucla"],
    "WAT" =>
    ["Africa/Lagos","Africa/Luanda","Africa/Malabo","Africa/Niamey","Africa/Douala",
      "Africa/Bangui","Africa/Ndjamena","Africa/Porto-Novo","Africa/Brazzaville",
      "Africa/Kinshasa","Africa/Libreville"],
    "MEST" => ["MET"],
    "PDT" =>
    ["PST8PDT","America/Vancouver","America/Ensenada","US/Pacific","Canada/Pacific",
      "America/Tijuana","America/Santa_Isabel","America/Los_Angeles","Mexico/BajaNorte"],
    "-01" => ["America/Scoresbysund","Atlantic/Azores","Etc/GMT+1","Atlantic/Cape_Verde"],
    "+08/+09" => ["Asia/Choibalsan","Asia/Ulan_Bator","Asia/Ulaanbaatar"],
    "+08" =>
    ["Asia/Singapore","Asia/Kuala_Lumpur","Etc/GMT-8","Asia/Irkutsk","Asia/Kuching",
      "Asia/Brunei","Singapore"],
    "EST" =>
    ["America/Indianapolis","America/Nassau","America/Detroit","America/Toronto","EST5EDT",
      "America/Indiana/Marengo","US/Michigan","America/Pangnirtung","Canada/Eastern",
      "America/Cancun","America/Port-au-Prince","America/Iqaluit",
      "America/Indiana/Indianapolis","US/Eastern","EST","America/Thunder_Bay",
      "America/New_York","America/Louisville","America/Montreal","America/Indiana/Winamac",
      "America/Atikokan","America/Indiana/Petersburg","America/Jamaica","America/Nipigon",
      "America/Kentucky/Monticello","Jamaica","America/Indiana/Vevay","America/Cayman",
      "America/Grand_Turk","US/East-Indiana","America/Indiana/Vincennes",
      "America/Kentucky/Louisville","America/Coral_Harbour","America/Fort_Wayne",
      "America/Panama"],
    "PST" =>
    ["PST8PDT","America/Vancouver","America/Ensenada","Asia/Manila","US/Pacific",
      "Canada/Pacific","America/Tijuana","America/Santa_Isabel","America/Los_Angeles",
      "Mexico/BajaNorte"],
    "HKT" => ["Asia/Hong_Kong","Hongkong"],
    "WIB" => ["Asia/Jakarta","Asia/Pontianak"],
    "+11/+12" => ["Pacific/Noumea","Pacific/Efate"],
    "+07/+08" => ["Asia/Hovd"],
    "-12" => ["Etc/GMT+12"],
    "+1030" => ["Australia/Lord_Howe","Australia/LHI"],
    "AKST" =>
    ["America/Yakutat","US/Alaska","America/Sitka","America/Nome","America/Metlakatla",
      "America/Juneau","America/Anchorage"],
    "+04" =>
    ["Europe/Astrakhan","Asia/Dubai","Europe/Ulyanovsk","Europe/Samara","Asia/Muscat",
      "Indian/Mahe","Europe/Saratov","Indian/Reunion","Etc/GMT-4","Asia/Tbilisi"],
    "-11" => ["Pacific/Niue","Etc/GMT+11"],
    "WIT" => ["Asia/Jayapura"],
    "UTC" => ["Etc/Zulu","Etc/UTC","Etc/UCT","Universal","UCT","UTC","Zulu","Etc/Universal"],
    "EET" =>
    ["Europe/Riga","Europe/Zaporozhye","Europe/Athens","Asia/Famagusta","Europe/Nicosia",
      "Asia/Damascus","Asia/Hebron","Europe/Kiev","Africa/Cairo","Africa/Tripoli","EET",
      "Europe/Kaliningrad","Egypt","Europe/Vilnius","Europe/Tallinn","Asia/Amman",
      "Europe/Tiraspol","Asia/Gaza","Europe/Uzhgorod","Asia/Nicosia","Europe/Chisinau",
      "Europe/Helsinki","Europe/Bucharest","Europe/Mariehamn","Europe/Sofia","Asia/Beirut",
      "Libya"],
    "-06" => ["Pacific/Easter","Etc/GMT+6","Chile/EasterIsland"],
    "+02" => ["Etc/GMT-2","Antarctica/Troll"],
    "+03" =>
    ["Asia/Qatar","Asia/Bahrain","Europe/Volgograd","Asia/Aden","Europe/Minsk",
      "Europe/Kirov","Asia/Kuwait","Antarctica/Syowa","Europe/Istanbul","Asia/Riyadh",
      "Turkey","Asia/Istanbul","Etc/GMT-3"],
    "+0545" => ["Asia/Katmandu","Asia/Kathmandu"],
    "BST" =>
    ["Europe/Isle_of_Man","GB-Eire","Europe/Belfast","Europe/Jersey","Europe/London","GB",
      "Europe/Guernsey"],
    "+14" => ["Pacific/Kiritimati","Etc/GMT-14","Pacific/Apia"],
    "ACDT" =>
    ["Australia/Yancowinna","Australia/Broken_Hill","Australia/South","Australia/Adelaide"],
    "-04/-03" => ["America/Cuiaba","America/Campo_Grande"],
    "HST" =>
    ["Pacific/Johnston","America/Adak","US/Hawaii","HST","US/Aleutian","America/Atka",
      "Pacific/Honolulu"],
    "+1245" => ["NZ-CHAT","Pacific/Chatham"],
    "HDT" => ["America/Adak","US/Aleutian","America/Atka"],
    "+13/+14" => ["Pacific/Tongatapu"],
    "SST" => ["Pacific/Midway","Pacific/Pago_Pago","Pacific/Samoa","US/Samoa"],
    "+0530" => ["Asia/Colombo"],
    "-03" =>
    ["America/Punta_Arenas","America/Santiago","America/Argentina/La_Rioja",
      "America/Araguaina","Etc/GMT+3","America/Argentina/Jujuy","America/Argentina/San_Juan",
      "America/Paramaribo","America/Argentina/Catamarca","America/Catamarca",
      "Antarctica/Rothera","America/Argentina/Salta","America/Cayenne","America/Mendoza",
      "America/Nuuk","America/Belem","America/Argentina/Ushuaia",
      "America/Argentina/Rio_Gallegos","America/Fortaleza","America/Maceio",
      "America/Asuncion","America/Miquelon","Atlantic/Stanley","America/Jujuy",
      "Chile/Continental","America/Argentina/Mendoza","America/Godthab","America/Bahia",
      "America/Recife","America/Argentina/San_Luis","America/Santarem","Antarctica/Palmer",
      "America/Argentina/ComodRivadavia"],
    "AST" =>
    ["America/Anguilla","America/Aruba","America/Antigua","America/St_Vincent",
      "America/Martinique","America/Port_of_Spain","America/Dominica","America/St_Thomas",
      "America/St_Lucia","America/Lower_Princes","America/Blanc-Sablon","America/Montserrat",
      "Atlantic/Bermuda","America/Halifax","America/Marigot","America/Barbados",
      "America/Puerto_Rico","America/Kralendijk","America/Grenada","America/Thule",
      "Canada/Atlantic","America/Curacao","America/Guadeloupe","America/Tortola",
      "America/Virgin","America/Goose_Bay","America/St_Barthelemy","America/Glace_Bay",
      "America/St_Kitts","America/Santo_Domingo","America/Moncton"],
    "EAT" =>
    ["Africa/Addis_Ababa","Africa/Nairobi","Indian/Antananarivo","Africa/Asmera",
      "Africa/Kampala","Africa/Dar_es_Salaam","Africa/Mogadishu","Indian/Comoro",
      "Africa/Asmara","Africa/Djibouti","Indian/Mayotte"],
    "-08" => ["Etc/GMT+8","Pacific/Pitcairn"],
    "+01" => ["Africa/Casablanca","Etc/GMT-1","Africa/El_Aaiun"],
    "-02" =>
    ["Atlantic/South_Georgia","America/Nuuk","Etc/GMT+2","America/Noronha",
      "America/Miquelon","Brazil/DeNoronha","America/Godthab"],
    "+06/+07" => ["Asia/Dhaka","Asia/Dacca"],
    "IDT" => ["Israel","Asia/Tel_Aviv","Asia/Jerusalem"],
    "ACST" =>
    ["Australia/Yancowinna","Australia/Darwin","Australia/Broken_Hill","Australia/South",
      "Australia/North","Australia/Adelaide"],
    "MSK" => ["Europe/Moscow","W-SU","Europe/Simferopol"],
    "+00" =>
    ["Africa/Casablanca","America/Scoresbysund","Atlantic/Azores","Africa/El_Aaiun",
      "Antarctica/Troll"],
    "MET" => ["MET"],
    "+0330" => ["Iran","Asia/Tehran"],
    "EEST" =>
    ["Europe/Riga","Europe/Zaporozhye","Europe/Athens","Asia/Famagusta","Europe/Nicosia",
      "Asia/Damascus","Asia/Hebron","Europe/Kiev","EET","Europe/Vilnius","Europe/Tallinn",
      "Asia/Amman","Europe/Tiraspol","Asia/Gaza","Europe/Uzhgorod","Asia/Nicosia",
      "Europe/Chisinau","Europe/Helsinki","Europe/Bucharest","Europe/Mariehamn",
      "Europe/Sofia","Asia/Beirut"],
    "NZDT" => ["Antarctica/South_Pole","NZ","Pacific/Auckland","Antarctica/McMurdo"],
    "PKT" => ["Asia/Karachi"],
    "KST" => ["ROK","Asia/Pyongyang","Asia/Seoul"],
    "-06/-05" => ["Pacific/Galapagos"],
    "AKDT" =>
    ["America/Yakutat","US/Alaska","America/Sitka","America/Nome","America/Metlakatla",
      "America/Juneau","America/Anchorage"],
    "-09" => ["Pacific/Gambier","Etc/GMT+9"],
    "-03/-02" =>
    ["America/Argentina/Buenos_Aires","Brazil/East","America/Buenos_Aires",
      "America/Sao_Paulo","America/Cordoba","America/Rosario","America/Montevideo",
      "America/Argentina/Tucuman","America/Argentina/Cordoba"],
    "-04" =>
    ["America/Santiago","America/Caracas","Brazil/West","America/Porto_Velho",
      "America/La_Paz","Etc/GMT+4","America/Asuncion","America/Manaus","Chile/Continental",
      "America/Guyana","America/Boa_Vista"],
    "CET" =>
    ["Europe/Prague","Europe/Malta","Europe/Vatican","Europe/Belgrade","Europe/Monaco",
      "Europe/Copenhagen","Europe/Rome","Europe/Brussels","Africa/Algiers","Europe/Sarajevo",
      "Europe/Tirane","Europe/Vienna","Arctic/Longyearbyen","Europe/Paris","Europe/Warsaw",
      "Europe/Skopje","Europe/Andorra","Poland","Europe/Luxembourg","Europe/San_Marino",
      "Europe/Madrid","Europe/Vaduz","Europe/Busingen","Europe/Bratislava","Africa/Ceuta",
      "Europe/Zurich","Europe/Oslo","Africa/Tunis","Europe/Zagreb","Europe/Budapest",
      "Europe/Berlin","CET","Europe/Stockholm","Europe/Podgorica","Europe/Ljubljana",
      "Europe/Amsterdam","Atlantic/Jan_Mayen","Europe/Gibraltar"],
    "+1345" => ["NZ-CHAT","Pacific/Chatham"],
    "+0630" => ["Asia/Yangon","Indian/Cocos","Asia/Rangoon"],
    "WITA" => ["Asia/Ujung_Pandang","Asia/Makassar"],
    "+06" =>
    ["Asia/Thimbu","Antarctica/Vostok","Indian/Chagos","Asia/Thimphu","Etc/GMT-6",
      "Asia/Bishkek","Asia/Almaty","Asia/Kashgar","Asia/Omsk","Asia/Urumqi","Asia/Qostanay"],
    "CDT" =>
    ["America/Winnipeg","America/Chicago","CST6CDT","America/Resolute",
      "America/North_Dakota/Beulah","Cuba","America/Havana","America/North_Dakota/New_Salem",
      "America/Mexico_City","Canada/Central","America/Menominee","America/Knox_IN",
      "America/North_Dakota/Center","America/Indiana/Knox","US/Indiana-Starke",
      "America/Indiana/Tell_City","America/Matamoros","Mexico/General",
      "America/Rankin_Inlet","America/Monterrey","US/Central","America/Rainy_River",
      "America/Merida","America/Bahia_Banderas"],
    "AWST" => ["Australia/Perth","Australia/West"],
    "+10" =>
    ["Asia/Vladivostok","Pacific/Truk","Asia/Ust-Nera","Pacific/Yap","Pacific/Port_Moresby",
      "Etc/GMT-10","Pacific/Chuuk","Antarctica/DumontDUrville"],
    "CST" =>
    ["America/Winnipeg","America/Chicago","America/Swift_Current","CST6CDT",
      "America/Resolute","Asia/Shanghai","ROC","America/El_Salvador",
      "America/North_Dakota/Beulah","Canada/Saskatchewan","Asia/Chungking","Cuba",
      "Asia/Macau","America/Havana","America/North_Dakota/New_Salem","Asia/Chongqing",
      "America/Mexico_City","Asia/Macao","Canada/Central","America/Menominee",
      "America/Belize","America/Costa_Rica","America/Knox_IN","America/North_Dakota/Center",
      "America/Indiana/Knox","US/Indiana-Starke","PRC","America/Indiana/Tell_City",
      "America/Regina","America/Matamoros","Asia/Taipei","Mexico/General",
      "America/Rankin_Inlet","Asia/Harbin","America/Monterrey","America/Guatemala",
      "America/Managua","America/Tegucigalpa","US/Central","America/Rainy_River",
      "America/Merida","America/Bahia_Banderas"],
    "AEDT" =>
    ["Australia/NSW","Australia/Sydney","Australia/Currie","Australia/Canberra",
      "Australia/ACT","Antarctica/Macquarie","Australia/Victoria","Australia/Tasmania",
      "Australia/Melbourne","Australia/Hobart"],
    "NZST" => ["Antarctica/South_Pole","NZ","Pacific/Auckland","Antarctica/McMurdo"],
    "-10" => ["Pacific/Tahiti","Etc/GMT+10"],
    "CAT" =>
    ["Africa/Lubumbashi","Africa/Maputo","Africa/Kigali","Africa/Blantyre",
      "Africa/Khartoum","Africa/Lusaka","Africa/Bujumbura","Africa/Windhoek",
      "Africa/Gaborone","Africa/Juba","Africa/Harare"],
    "-10/-0930" => ["Pacific/Rarotonga"],
    "AEST" =>
    ["Australia/NSW","Australia/Sydney","Australia/Currie","Australia/Canberra",
      "Australia/ACT","Antarctica/Macquarie","Australia/Brisbane","Australia/Victoria",
      "Australia/Queensland","Australia/Lindeman","Australia/Tasmania","Australia/Melbourne",
      "Australia/Hobart"],
    "JST" => ["Asia/Tokyo","Japan"],
    "GMT" =>
    ["Atlantic/St_Helena","Africa/Banjul","Etc/Greenwich","Europe/Isle_of_Man",
      "Africa/Timbuktu","GB-Eire","Etc/GMT-0","America/Danmarkshavn","Africa/Sao_Tome",
      "Africa/Freetown","Europe/Belfast","Iceland","Africa/Monrovia","Atlantic/Reykjavik",
      "Europe/Jersey","Africa/Lome","Africa/Ouagadougou","Europe/Dublin","Eire",
      "Africa/Abidjan","Africa/Dakar","Etc/GMT","Africa/Accra","GMT+0","Africa/Conakry",
      "Europe/London","Africa/Bissau","GMT-0","GMT0","Africa/Nouakchott","GB","Etc/GMT+0",
      "Greenwich","GMT","Africa/Bamako","Europe/Guernsey","Etc/GMT0"],
    "IST" =>
    ["Asia/Calcutta","Israel","Asia/Kolkata","Europe/Dublin","Eire","Asia/Tel_Aviv",
      "Asia/Jerusalem"],
    "MST" =>
    ["Canada/Yukon","America/Yellowknife","America/Whitehorse","America/Ojinaga","MST7MDT",
      "America/Hermosillo","Mexico/BajaSur","America/Dawson_Creek","US/Mountain",
      "Canada/Mountain","America/Mazatlan","America/Shiprock","Navajo","America/Creston",
      "America/Chihuahua","America/Fort_Nelson","US/Arizona","America/Denver",
      "America/Edmonton","America/Dawson","America/Boise","America/Inuvik",
      "America/Cambridge_Bay","America/Phoenix","MST"],
    "CEST" =>
    ["Europe/Prague","Europe/Malta","Europe/Vatican","Europe/Belgrade","Europe/Monaco",
      "Europe/Copenhagen","Europe/Rome","Europe/Brussels","Europe/Sarajevo","Europe/Tirane",
      "Europe/Vienna","Arctic/Longyearbyen","Europe/Paris","Europe/Warsaw","Europe/Skopje",
      "Europe/Andorra","Poland","Europe/Luxembourg","Europe/San_Marino","Europe/Madrid",
      "Europe/Vaduz","Europe/Busingen","Europe/Bratislava","Africa/Ceuta","Europe/Zurich",
      "Europe/Oslo","Europe/Zagreb","Europe/Budapest","Europe/Berlin","CET",
      "Europe/Stockholm","Europe/Podgorica","Europe/Ljubljana","Europe/Amsterdam",
      "Atlantic/Jan_Mayen","Europe/Gibraltar"],
    "SAST" => ["Africa/Johannesburg","Africa/Mbabane","Africa/Maseru"],
    "+12" =>
    ["Pacific/Nauru","Pacific/Fiji","Pacific/Kwajalein","Asia/Kamchatka","Pacific/Wallis",
      "Pacific/Majuro","Pacific/Norfolk","Kwajalein","Etc/GMT-12","Pacific/Funafuti",
      "Pacific/Tarawa","Pacific/Wake","Asia/Anadyr"],
    "ADT" =>
    ["Atlantic/Bermuda","America/Halifax","America/Thule","Canada/Atlantic",
      "America/Goose_Bay","America/Glace_Bay","America/Moncton"]}).
